### ISSUE TITLE
Grant Type Error on `login` v0.2.0

### ISSUE THREAD

**Issue by britton-jb** [jeffweiss/forcex#1]
I'm attempting to utilize `Forcex` to interact with the Saleforce API, and I'm currently getting the following return error from the `login` method:

```
bad return value: {:error, %{"error" => "invalid_grant", "error_description" => "authentication failure"}
```

I'm calling `login` with the parameters `pid, username, password, client_id, client_secret`

Before I call `Forcex.login` I'm currently calling `Forcex.start` with `%{ username: username, password: password, client_id: client_id, client_secret: client_secret }`

My application is currently setup as a connected app in Salesforce.

There's likely something I'm missing here, but it appears to be a bug to me based on the documentation?

**Comment by jeffweiss** [comment]
@britton-jb thanks for the bug report, I'll try to take a look at it this evening.

**Comment by britton-jb** [comment]
Thanks @jeffweiss - and thanks for putting this library out here into the open for the Elixir community.

**Comment by jeffweiss** [comment]
@britton-jb Hmm.. I am able to login. I think I might know what the issue is though. The 3rd parameter is supposed to be a concatenation of both the password and the security token. I'm certainly not making that clear enough in the documentation.

I am running into a host of other issues **after** logging though. I originally wrote this library as a part of a prototype and haven't even attempted to use it in quite some time. It needs a significant refactor. If you can bear with me, I'll begin cleaning it up.

**Comment by jeffweiss** [comment]
Ah... I see what's going on now. When I initially created, HTTPoison returned headers in the a map, now the headers are a list of tuples.

I'll see what I can do to get it functional before it undergoes the massive refactor to clear away mistakes past-Jeff made.

**Comment by jeffweiss** [comment]
@britton-jb You should be set to go with [0.2.1](https://hex.pm/packages/forcex/0.2.1)!

I will try to illustrate it better in the documentation, but in order to login, you need 5 pieces of information:

1. username
2. password
3. security token
4. consumer/client key
5. consumer/client secret

When sent the `Forcex.login/5`, the `password` and `security token` on concatenated. For example,

1. username - `jeff.weiss@example.com`
2. password - `my_super_secret_password`
3. security token - `SECRET_USER_SECURITY_TOKEN_EMAILED_FROM_SALESFORCE`
4. consumer/client key - `OAUTH_APPLICATION_KEY`
5. consumer/client secret - `OAUTH_APPLICATION_SECRET`

The call to `Forcex.login/5` would look like:

```elixir
{:ok, pid} = Forcex.start
Forcex.login( pid, 
              "jeff.weiss@example.com",
              "my_super_secret_passwordSECRET_USER_SECURITY_TOKEN_EMAILED_FROM_SALESFORCE",
              "OAUTH_APPLICATION_KEY", 
              "OAUTH_APPLICATION_SECRET")
```

If you run into additional problems, please let me know!
